# Generated by Django 3.2.6 on 2021-08-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundmenu_spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_1_menu',
            name='class_1_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class_2_menu',
            name='class_2_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class_3_menu',
            name='class_3_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class_3_to_class4',
            name='class_3_class_4_id_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class_4_menu',
            name='class_4_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class_5_menu',
            name='class_5_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_primary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
