# Generated by Django 3.2.6 on 2021-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundmenu_spa', '0002_auto_20210808_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='takeout',
            field=models.BooleanField(default=False),
        ),
    ]
