# Generated by Django 3.2.6 on 2021-08-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundmenu_spa', '0003_alter_store_takeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='tables',
            new_name='seating_capacity',
        ),
    ]
