# Generated by Django 3.2.6 on 2021-08-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundmenu_spa', '0004_rename_tables_store_seating_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='takeout',
            new_name='takeout_support',
        ),
    ]
